<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PF4A59NC" failures="0" tests="4" name="TestNgAssertions.HardAssertion" time="55.296" errors="1" timestamp="2024-10-18T20:18:07 IST" skipped="0">
  <testcase classname="TestNgAssertions.HardAssertion" name="verifyTitle" time="16.103"/>
  <system-out/>
  <testcase classname="TestNgAssertions.HardAssertion" name="enterUsername" time="5.033">
    <error message="Method TestNgAssertions.HardAssertion.enterUsername() didn&#039;t finish within the time-out 5000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method TestNgAssertions.HardAssertion.enterUsername() didn't finish within the time-out 5000
at TestNgAssertions.HardAssertion.enterUsername(HardAssertion.java:64)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </error>
  </testcase> <!-- enterUsername -->
  <system-out/>
  <testcase classname="TestNgAssertions.HardAssertion" name="enterPassword" time="34.106"/>
  <system-out/>
  <testcase classname="TestNgAssertions.HardAssertion" name="clickLogin" time="0.054"/>
  <system-out/>
</testsuite> <!-- TestNgAssertions.HardAssertion -->
